apiVersion: apps/v1
kind: Deployment
metadata:
  name: permisos-service
  labels:
    app: permisos-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: permisos-service
  template:
    metadata:
      labels:
        app: permisos-service
    spec:
      imagePullSecrets:
        - name: dockerhub-credenciales # mi secret de las credenciales de dockerhub
      containers:
        - name: permisos-service
          image: carlitossteven/permisos-service:v3.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__ConexionDB #Tiene que ser el nombre que se pone en el appsettings.json de la api
              valueFrom:
                secretKeyRef:
                  name: db-secret #NOMBRE DEL SECRETO
                  key: DB_CONNECTION #NOMBRE DE LA LLAVE DENTRO DEL SECRETO
            - name: Jwt__Secret
              valueFrom:
                secretKeyRef:
                  name: db-secret #NOMBRE DEL SECRETO
                  key: JWT_SECRET #NOMBRE DE LA LLAVE DENTRO DEL SECRETO
